spring.application.name=auth-service
server.port=8083

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
management.endpoint.health.probes.enabled=true

spring.datasource.url=${AUTH_DB_URL}
spring.datasource.username=${AUTH_DB_USERNAME}
spring.datasource.password=${AUTH_DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

eureka.client.serviceUrl.defaultZone=${EUREKA_SERVER}
eureka.instance.prefer-ip-address=true

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS}
